Added Erik Serrano bio under _members folder
WayScience/waysciencelab.com pull request #12
Opened 2022-06-01 18:01 UTC by axiomcura

Hey @gwaygenomics I added my bio into the `_members` folder. Take a look

2022-06-03 15:27 UTC, gwaygenomics requested changes
Take a look when you get a chance

2022-06-03 15:27 UTC, gwaygenomics commented on _members/erik-serrano.md
> +image:
Please add image!

2022-06-03 15:27 UTC, gwaygenomics commented on _members/erik-serrano.md
> +  orcid: 0000-0002-0503-9348
Please add your [ORCID](https://orcid.org/)

2022-06-03 15:27 UTC, gwaygenomics commented on _members/erik-serrano.md
> +  home-page: waysciencelab.com
maybe make it your github profile page?

2022-06-03 15:27 UTC, gwaygenomics commented on _members/erik-serrano.md
> +[ my  bio]
Please write a brief bio - see the site for examples

2022-06-28 21:56 UTC, axiomcura commented
@gwaybio  added changes to my bio.

2022-06-28 23:03 UTC, gwaybio requested changes
Looks great! I corrected a couple typos and made grammar suggestions.

I'll merge after you address.

2022-06-28 23:03 UTC, gwaybio commented on _members/erik-serrano.md
> +Erik obtained his bachelors degree in Molecular Biology with a minor in chemistry at the [California State University, Northirdge (CSUN)](https://www.csun.edu/).
```suggestion
Erik obtained his bachelors degree in Molecular Biology with a minor in chemistry at the [California State University, Northridge (CSUN)](https://www.csun.edu/).
```

correct?

2022-06-28 23:03 UTC, gwaybio commented on _members/erik-serrano.md
> +Throughout his undergraduate degree, his research experience mainly pertained to developing computational methods to elucidate biological insights through the usage of protein dynamic data produced b
```suggestion
Throughout his undergraduate degree, he developed computational methods to elucidate biological insights from protein dynamic data produced by molecular dynamic simulations.
```

To correct grammar and brevity

2022-06-28 23:03 UTC, gwaybio commented on _members/erik-serrano.md
> +After graduating from CSUN, Erik did his post baccalaureate at [Cedar-Sinai Medical Center](https://www.cedars-sinai.edu/research/departments-institutes/biomedical-sciences.html) where his main job w
```suggestion
After graduating from CSUN, Erik did his post baccalaureate at [Cedar-Sinai Medical Center](https://www.cedars-sinai.edu/research/departments-institutes/biomedical-sciences.html) where he designed viral based nano-particles through the usage of computational protein modeling.
```

brevity

2022-06-28 23:03 UTC, gwaybio commented on _members/erik-serrano.md
> +He is fluent in Spanish and is currently learning Brazilian Portuguese to become his third language.
```suggestion
He is fluent in Spanish and is currently learning Brazilian Portuguese, which will become his third language.
```

2022-06-28 23:03 UTC, gwaybio commented on _members/erik-serrano.md
> +He is fluent in Spanish and is currently learning Brazilian Portuguese to become his third language.
You're also fluent in python! 😂

2022-06-28 23:32 UTC, axiomcura commented
@gwaybio addressed all suggestions!

2022-06-28 23:37 UTC, gwaybio approved these changes
👍

2022-06-28 23:38 UTC, merged